all:	Scanner.class Token.class

Scanner.class:	Scanner.java
	CLASSPATH=../../../../..:. javac Scanner.java
Token.class:	Token.java
	CLASSPATH=../../../../..:. javac Token.java

clean:
	rm -f *.class *~
