all:	ArrayType.class BasicType.class Type.class Types.class

ArrayType.class:	ArrayType.java
	CLASSPATH=../../../../..:. javac ArrayType.java
BasicType.class:	BasicType.java
	CLASSPATH=../../../../..:. javac BasicType.java
Type.class:	Type.java
	CLASSPATH=../../../../..:. javac Type.java
Types.class:	Types.java
	CLASSPATH=../../../../..:. javac Types.java

clean:
	rm -f *.class *~
